version: "3.5"

services:
  sidecar:
    image: docker.cetcxl.local/sidecar:1.0.5
    environment:
      - ETCD_ENDPOINT=https://etcd.cetcxl.com
      - ETCD_USERNAME=nw
      - ETCD_PASSWORD=P@ssw0rd
      - SIDECAR_PREFIX=sidecar
    ports:
      - "6000:5000"
    restart: always